version: '3'

services:
  postgresql:
    image: postgres
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data